/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 scene.gltf -t -o ConverseHT.tsx 
Author: abazibiz (https://sketchfab.com/abazibiz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sneakers-689c29ec3a8a4f44b32f616bcb97cfaa
Title: sneakers
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    shoes_3_cons_mat_0: THREE.Mesh
  }
  materials: {
    cons_mat: THREE.MeshStandardMaterial
  }
  // animations: GLTFAction[]
}

export function ConverseHT(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/converse-ht/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null} scale={20}>
      <mesh geometry={nodes.shoes_3_cons_mat_0.geometry} material={materials.cons_mat} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
