/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 scene.gltf -t -o guitar-sg.tsx 
Author: Ryan_Nein (https://sketchfab.com/Ryan_Nein)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gibson-sg-guitar-2007af7561fe46958d1f7e92dff8a40d
Title: Gibson SG Guitar
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2: THREE.Mesh
    Object_3: THREE.Mesh
    Object_4: THREE.Mesh
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
  }
  materials: {
    ['Material.001']: THREE.MeshStandardMaterial
  }
}

export function GuitarSG(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/guitar-sg/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group >
        <mesh rotation={[-Math.PI/2, 0, -Math.PI/2]} geometry={nodes.Object_2.geometry} material={materials['Material.001']} />
        <mesh rotation={[-Math.PI/2, 0, -Math.PI/2]} geometry={nodes.Object_3.geometry} material={materials['Material.001']} />
        <mesh rotation={[-Math.PI/2, 0, -Math.PI/2]} geometry={nodes.Object_4.geometry} material={materials['Material.001']} />
        <mesh rotation={[-Math.PI/2, 0, -Math.PI/2]} geometry={nodes.Object_5.geometry} material={materials['Material.001']} />
        <mesh rotation={[-Math.PI/2, 0, -Math.PI/2]} geometry={nodes.Object_6.geometry} material={materials['Material.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/guitar-sg/scene.gltf')
