/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 scene.gltf -t -o katana.tsx 
Author: T-Art (https://sketchfab.com/person-x)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/katana-5bc192b777544d58a185845ed495597f
Title: Katana
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['Tsuba_mat-material']: THREE.Mesh
    ['Tsuka_mat-material']: THREE.Mesh
    ['Saya_mat-material']: THREE.Mesh
    ['Habaki_mat-material']: THREE.Mesh
    ['Blade_mat-material']: THREE.Mesh
  }
  materials: {
    Tsuba_mat: THREE.MeshStandardMaterial
    Tsuka_mat: THREE.MeshStandardMaterial
    Saya_mat: THREE.MeshStandardMaterial
    Habaki_mat: THREE.MeshStandardMaterial
    Blade_mat: THREE.MeshStandardMaterial
  }
}

export function Katana(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/katana/scene.gltf') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group>
        <mesh geometry={nodes['Tsuba_mat-material'].geometry} material={materials.Tsuba_mat} position={[0, -0.007, -0.02]} rotation={[Math.PI / 2, 0, 0]} scale={[0.069, 0.114, 0.069]} />
        <mesh geometry={nodes['Tsuka_mat-material'].geometry} material={materials.Tsuka_mat} position={[0, -0.007, -0.02]} rotation={[Math.PI / 2, 0, 0]} scale={[0.069, 0.114, 0.069]} />
        <mesh geometry={nodes['Saya_mat-material'].geometry} material={materials.Saya_mat} position={[0, -0.007, -0.596]} rotation={[Math.PI / 2, 0, 0]} scale={[0.209, 0.161, 0.157]} />
        <mesh geometry={nodes['Habaki_mat-material'].geometry} material={materials.Habaki_mat} position={[0, -0.007, -0.02]} rotation={[Math.PI / 2, 0, 0]} scale={[0.069, 0.114, 0.069]} />
        <mesh geometry={nodes['Blade_mat-material'].geometry} material={materials.Blade_mat} position={[0, -0.007, -0.02]} rotation={[Math.PI / 2, 0, 0]} scale={[0.069, 0.114, 0.069]} />
      </group>
    </group>
  )
}

useGLTF.preload('/katana/scene.gltf')
