/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 scene.gltf -t -o NikeAirJordan.tsx 
Author: freemen (https://sketchfab.com/lox148822847)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/nike-air-force-1-dc13b616608342909c798d57a313798f
Title: Nike Air force 1
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_10: THREE.Mesh
    Object_13: THREE.Mesh
    Object_16: THREE.Mesh
    Object_19: THREE.Mesh
    Object_22: THREE.Mesh
    Object_26: THREE.Mesh
    Object_29: THREE.Mesh
    Object_32: THREE.Mesh
    Object_35: THREE.Mesh
    Object_38: THREE.Mesh
    Object_41: THREE.Mesh
    Object_44: THREE.Mesh
    Object_47: THREE.Mesh
    Object_50: THREE.Mesh
    Object_53: THREE.Mesh
    Object_56: THREE.Mesh
    Object_59: THREE.Mesh
    Object_62: THREE.Mesh
    Object_65: THREE.Mesh
    Object_68: THREE.Mesh
    Object_71: THREE.Mesh
    Object_74: THREE.Mesh
    Object_77: THREE.Mesh
    Object_80: THREE.Mesh
    Object_83: THREE.Mesh
    Object_86: THREE.Mesh
    Object_89: THREE.Mesh
    Object_92: THREE.Mesh
    Object_95: THREE.Mesh
    Object_98: THREE.Mesh
    Object_101: THREE.Mesh
    Object_104: THREE.Mesh
    Object_107: THREE.Mesh
    Object_110: THREE.Mesh
    Object_113: THREE.Mesh
    Object_116: THREE.Mesh
    Object_119: THREE.Mesh
    Object_122: THREE.Mesh
    Object_125: THREE.Mesh
    Object_128: THREE.Mesh
    Object_131: THREE.Mesh
    Object_134: THREE.Mesh
    Object_137: THREE.Mesh
    Object_140: THREE.Mesh
    Object_143: THREE.Mesh
    Object_146: THREE.Mesh
    Object_149: THREE.Mesh
    Object_152: THREE.Mesh
    Object_155: THREE.Mesh
    Object_158: THREE.Mesh
    Object_161: THREE.Mesh
    Object_164: THREE.Mesh
    Object_167: THREE.Mesh
    Object_170: THREE.Mesh
    Object_173: THREE.Mesh
    Object_176: THREE.Mesh
    Object_179: THREE.Mesh
    Object_182: THREE.Mesh
    Object_185: THREE.Mesh
    Object_188: THREE.Mesh
    Object_191: THREE.Mesh
    Object_194: THREE.Mesh
    Object_197: THREE.Mesh
    Object_200: THREE.Mesh
    Object_203: THREE.Mesh
    Object_206: THREE.Mesh
    Object_209: THREE.Mesh
    Object_212: THREE.Mesh
    Object_215: THREE.Mesh
    Object_218: THREE.Mesh
    Object_221: THREE.Mesh
    Object_224: THREE.Mesh
    Object_227: THREE.Mesh
    Object_230: THREE.Mesh
    Object_233: THREE.Mesh
    Object_236: THREE.Mesh
    Object_239: THREE.Mesh
    Object_242: THREE.Mesh
    Object_245: THREE.Mesh
    Object_248: THREE.Mesh
    Object_251: THREE.Mesh
    Object_254: THREE.Mesh
    Object_257: THREE.Mesh
    Object_259: THREE.Mesh
    Object_261: THREE.Mesh
    Object_263: THREE.Mesh
    Object_265: THREE.Mesh
    Object_267: THREE.Mesh
    Object_269: THREE.Mesh
    Object_271: THREE.Mesh
    Object_273: THREE.Mesh
    Object_275: THREE.Mesh
    Object_277: THREE.Mesh
    Object_279: THREE.Mesh
    Object_281: THREE.Mesh
    Object_283: THREE.Mesh
    Object_285: THREE.Mesh
    Object_287: THREE.Mesh
    Object_289: THREE.Mesh
    Object_291: THREE.Mesh
    Object_293: THREE.Mesh
    Object_295: THREE.Mesh
    Object_297: THREE.Mesh
    Object_299: THREE.Mesh
    Object_301: THREE.Mesh
    Object_303: THREE.Mesh
    Object_305: THREE.Mesh
    Object_307: THREE.Mesh
    Object_309: THREE.Mesh
    Object_311: THREE.Mesh
    Object_313: THREE.Mesh
    Object_315: THREE.Mesh
    Object_317: THREE.Mesh
    Object_319: THREE.Mesh
    Object_321: THREE.Mesh
    Object_323: THREE.Mesh
    Object_325: THREE.Mesh
    Object_327: THREE.Mesh
    Object_329: THREE.Mesh
    Object_331: THREE.Mesh
  }
  materials: {
    ['Scene_-_Root_1_1']: THREE.MeshStandardMaterial
    ['Scene_-_Root_1_1.001']: THREE.MeshStandardMaterial
    Default_Topstitch_2348: THREE.MeshStandardMaterial
    Topstitch_1_1860109: THREE.MeshStandardMaterial
    ['Leather_Copy_1_1748881.001']: THREE.MeshStandardMaterial
    ['Cotton_Twill_1680397.001']: THREE.MeshStandardMaterial
    Leather_2226: THREE.MeshStandardMaterial
    Leather_Copy_1_1748881: THREE.MeshStandardMaterial
    Cotton_Twill_1680397: THREE.MeshStandardMaterial
    Cotton_Twill_1463669: THREE.MeshStandardMaterial
    ['Cotton_Twill_1680397.002']: THREE.MeshStandardMaterial
    ['Cotton_Twill_1680397.003']: THREE.MeshStandardMaterial
    ['Leather_2226.001']: THREE.MeshStandardMaterial
  }
  // animations: GLTFAction[]
}

export function NikeAirJordan(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/nike-air-jordan/scene.gltf') as GLTFResult
  return (
    <group scale={15} {...props} dispose={null}>
      <mesh geometry={nodes.Object_8.geometry} material={materials['Scene_-_Root_1_1']} />
      <mesh geometry={nodes.Object_9.geometry} material={materials['Scene_-_Root_1_1']} />
      <mesh geometry={nodes.Object_10.geometry} material={materials['Scene_-_Root_1_1']} />
      <mesh geometry={nodes.Object_13.geometry} material={materials['Scene_-_Root_1_1']} />
      <mesh geometry={nodes.Object_16.geometry} material={materials['Scene_-_Root_1_1']} />
      <mesh geometry={nodes.Object_19.geometry} material={materials['Scene_-_Root_1_1']} />
      <mesh geometry={nodes.Object_22.geometry} material={materials['Scene_-_Root_1_1.001']} />
      <mesh geometry={nodes.Object_26.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_29.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_32.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_35.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_38.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_41.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_44.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_47.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_50.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_53.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_56.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_59.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_62.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_65.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_68.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_71.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_74.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_77.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_80.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_83.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_86.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_89.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_92.geometry} material={materials.Topstitch_1_1860109} />
      <mesh geometry={nodes.Object_95.geometry} material={materials.Topstitch_1_1860109} />
      <mesh geometry={nodes.Object_98.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_101.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_104.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_107.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_110.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_113.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_116.geometry} material={materials.Topstitch_1_1860109} />
      <mesh geometry={nodes.Object_119.geometry} material={materials.Topstitch_1_1860109} />
      <mesh geometry={nodes.Object_122.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_125.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_128.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_131.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_134.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_137.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_140.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_143.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_146.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_149.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_152.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_155.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_158.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_161.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_164.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_167.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_170.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_173.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_176.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_179.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_182.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_185.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_188.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_191.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_194.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_197.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_200.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_203.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_206.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_209.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_212.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_215.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_218.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_221.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_224.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_227.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_230.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_233.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_236.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_239.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_242.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_245.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_248.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_251.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_254.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_257.geometry} material={materials.Default_Topstitch_2348} />
      <mesh geometry={nodes.Object_259.geometry} material={materials['Leather_Copy_1_1748881.001']} />
      <mesh geometry={nodes.Object_261.geometry} material={materials['Leather_Copy_1_1748881.001']} />
      <mesh geometry={nodes.Object_263.geometry} material={materials['Leather_Copy_1_1748881.001']} />
      <mesh geometry={nodes.Object_265.geometry} material={materials['Leather_Copy_1_1748881.001']} />
      <mesh geometry={nodes.Object_267.geometry} material={materials['Leather_Copy_1_1748881.001']} />
      <mesh geometry={nodes.Object_269.geometry} material={materials['Leather_Copy_1_1748881.001']} />
      <mesh geometry={nodes.Object_271.geometry} material={materials['Cotton_Twill_1680397.001']} />
      <mesh geometry={nodes.Object_273.geometry} material={materials['Cotton_Twill_1680397.001']} />
      <mesh geometry={nodes.Object_275.geometry} material={materials['Cotton_Twill_1680397.001']} />
      <mesh geometry={nodes.Object_277.geometry} material={materials['Cotton_Twill_1680397.001']} />
      <mesh geometry={nodes.Object_279.geometry} material={materials['Cotton_Twill_1680397.001']} />
      <mesh geometry={nodes.Object_281.geometry} material={materials['Cotton_Twill_1680397.001']} />
      <mesh geometry={nodes.Object_283.geometry} material={materials['Cotton_Twill_1680397.001']} />
      <mesh geometry={nodes.Object_285.geometry} material={materials['Cotton_Twill_1680397.001']} />
      <mesh geometry={nodes.Object_287.geometry} material={materials['Cotton_Twill_1680397.001']} />
      <mesh geometry={nodes.Object_289.geometry} material={materials['Cotton_Twill_1680397.001']} />
      <mesh geometry={nodes.Object_291.geometry} material={materials['Cotton_Twill_1680397.001']} />
      <mesh geometry={nodes.Object_293.geometry} material={materials['Cotton_Twill_1680397.001']} />
      <mesh geometry={nodes.Object_295.geometry} material={materials['Cotton_Twill_1680397.001']} />
      <mesh geometry={nodes.Object_297.geometry} material={materials['Leather_Copy_1_1748881.001']} />
      <mesh geometry={nodes.Object_299.geometry} material={materials.Leather_2226} />
      <mesh geometry={nodes.Object_301.geometry} material={materials.Leather_Copy_1_1748881} />
      <mesh geometry={nodes.Object_303.geometry} material={materials.Cotton_Twill_1680397} />
      <mesh geometry={nodes.Object_305.geometry} material={materials.Cotton_Twill_1463669} />
      <mesh geometry={nodes.Object_307.geometry} material={materials.Leather_2226} />
      <mesh geometry={nodes.Object_309.geometry} material={materials['Leather_Copy_1_1748881.001']} />
      <mesh geometry={nodes.Object_311.geometry} material={materials['Cotton_Twill_1680397.002']} />
      <mesh geometry={nodes.Object_313.geometry} material={materials['Cotton_Twill_1680397.003']} />
      <mesh geometry={nodes.Object_315.geometry} material={materials.Cotton_Twill_1463669} />
      <mesh geometry={nodes.Object_317.geometry} material={materials.Cotton_Twill_1463669} />
      <mesh geometry={nodes.Object_319.geometry} material={materials['Leather_2226.001']} />
      <mesh geometry={nodes.Object_321.geometry} material={materials['Leather_Copy_1_1748881.001']} />
      <mesh geometry={nodes.Object_323.geometry} material={materials['Leather_Copy_1_1748881.001']} />
      <mesh geometry={nodes.Object_325.geometry} material={materials['Leather_Copy_1_1748881.001']} />
      <mesh geometry={nodes.Object_327.geometry} material={materials['Leather_Copy_1_1748881.001']} />
      <mesh geometry={nodes.Object_329.geometry} material={materials['Leather_Copy_1_1748881.001']} />
      <mesh geometry={nodes.Object_331.geometry} material={materials['Leather_Copy_1_1748881.001']} />
    </group>
  )
}

useGLTF.preload('/nike-air-jordan/scene.gltf')
